### ISSUE TITLE
Quote mark symbol at the end of the template

### ISSUE THREAD

**Issue by aurorarq** [sistedes/sistedes.cls#1]
Hi,

Thank you for the template. I am using the template for regular papers in Overleaf and I see a single quotation mark symbol appearing at the end of the document. It doesn't seem to belong to the template text, as it also appears if I type my own text and replace the references. See the image below:

![screenshoot](https://user-images.githubusercontent.com/20265781/225868859-9bbfe5aa-5edf-48b7-806f-54108bd45919.jpg)

Could it be a typo or an error in the cls file?
Thanks!

**Comment by abelgomez** [comment]
Ops! I forgot to update the template in Overleaf with the latest version of the template.

The quote is added by a bug in hyperref/hyperxmp, when the title and/or authors are empty (because at the point of setting the PDF metadata are still not set).

The latest version of the template in https://raw.githubusercontent.com/sistedes/sistedes.template/master/sistedes.cls should work correctly.

Simply replace the contents of `sistedes.cls` in your Overleaf project with the file above.

I'll try to update the templates in Overleaf for future authors using it.

**Comment by aurorarq** [comment]
Done. It works. Thank you!

**Comment by abelgomez** [comment]
I have initiated the process to update the template project in Overleaf. Unfortunately, this is not an automated process: templates are manually approved by the Overleaf staff, and the process may take several days to be completed.

I'll leave this issue open for other authors' reference until the templates in Overleaf are up to date.

**Comment by abelgomez** [comment]
After four days (I initiated the process on March 17), the updated templates have been approved and are online.

Thanks for your patience! 😊
