### ISSUE TITLE
Broken template due to hyperxmp breaking changes

### ISSUE THREAD

**Issue by pjmolina** [sistedes/sistedes.cls#6]
Cloned the repo on Windows with latest MiKTeX. Tried to build the sample with: 
`pdflatex ejemplo-articulo-regular-en.tex`.

Getting this error on output:

```
! Package hyperxmp Error: hyperref must be loaded before hyperxmp.

See the hyperxmp package documentation for explanation.
Type  H <return>  for immediate help.
 ...
l.276 }

? H
Recent versions of hyperref and the LaTeX kernel inhibit
hyperxmp's ability to hook into hyperref's internals unless
hyperref is loaded first.`
``` 

**Expected behaivour:** build.

Related & proposed fix: https://github.com/borisveytsman/acmart/issues/505
Requiere `hyperref` before `hyperxmp`.

**Comment by abelgomez** [comment]
Hi Pedro,

thanks for spotting this.

This seems caused by an intentional change in hyperref v5.12 (released on Sept. 2023). Earlier versions would compile correctly, but to be fair, I noticed different behaviours depending on the LaTeX distribution/age when I tested the first version of the template (maybe caused by the changes in the kernel mentioned in the hyperxmp documentation).

The way the parameters of hyperref and hyperxmp are managed is a bit tricky (as you also noticed in #7).

Thanks!
